---

- name: Deploy a Web Application
  hosts: remote
  become: yes
  tasks:
    - name: Install all required dependencies
      apt: 
        name: "{{ item }}"
        state: present
      with_items:
        - python
        - python-setuptools
        - python-dev
        - build-essential
        - python3-pip
        - python3-mysqldb
    - include: tasks/deploy_db.yml
    - include: tasks/deploy_web.yml


        