---
# tasks file for python
- name: Install all required dependencies
  apt: 
    name: "{{ item }}"
    state: absent
  with_items:
    - python
    - python-setuptools
    - python-dev
    - build-essential
    - python3-pip
    - python3-mysqldb